/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgsiTimeseriesV2);
  }
})(this, function(expect, NgsiTimeseriesV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgsiTimeseriesV2.IndexedEntityAttribute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('IndexedEntityAttribute', function() {
    it('should create an instance of IndexedEntityAttribute', function() {
      // uncomment below and update the code to test IndexedEntityAttribute
      //var instane = new NgsiTimeseriesV2.IndexedEntityAttribute();
      //expect(instance).to.be.a(NgsiTimeseriesV2.IndexedEntityAttribute);
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instane = new NgsiTimeseriesV2.IndexedEntityAttribute();
      //expect(instance).to.be();
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instane = new NgsiTimeseriesV2.IndexedEntityAttribute();
      //expect(instance).to.be();
    });

    it('should have the property entityId (base name: "entityId")', function() {
      // uncomment below and update the code to test the property entityId
      //var instane = new NgsiTimeseriesV2.IndexedEntityAttribute();
      //expect(instance).to.be();
    });

    it('should have the property attrName (base name: "attrName")', function() {
      // uncomment below and update the code to test the property attrName
      //var instane = new NgsiTimeseriesV2.IndexedEntityAttribute();
      //expect(instance).to.be();
    });
  });
});
