# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_v2
from ngsi_v2.api.attribute_value_api import AttributeValueApi  # noqa: E501
from ngsi_v2.rest import ApiException


class TestAttributeValueApi(unittest.TestCase):
    """AttributeValueApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_v2.api.attribute_value_api.AttributeValueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attribute_value(self):
        """Test case for get_attribute_value

        """
        pass

    def test_update_attribute_value(self):
        """Test case for update_attribute_value

        """
        pass


if __name__ == '__main__':
    unittest.main()
