# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_v2
from ngsi_v2.api.subscriptions_api import SubscriptionsApi  # noqa: E501
from ngsi_v2.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_v2.api.subscriptions_api.SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_new_subscription(self):
        """Test case for create_a_new_subscription

        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        """
        pass

    def test_retrieve_subscription(self):
        """Test case for retrieve_subscription

        """
        pass

    def test_retrieve_subscriptions(self):
        """Test case for retrieve_subscriptions

        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        """
        pass


if __name__ == '__main__':
    unittest.main()
