# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_v2
from ngsi_v2.api.batch_operations_api import BatchOperationsApi  # noqa: E501
from ngsi_v2.rest import ApiException


class TestBatchOperationsApi(unittest.TestCase):
    """BatchOperationsApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_v2.api.batch_operations_api.BatchOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notify(self):
        """Test case for notify

        """
        pass

    def test_query(self):
        """Test case for query

        """
        pass

    def test_update(self):
        """Test case for update

        """
        pass


if __name__ == '__main__':
    unittest.main()
