# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_v2
from ngsi_v2.api.entities_api import EntitiesApi  # noqa: E501
from ngsi_v2.rest import ApiException


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_v2.api.entities_api.EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_entity(self):
        """Test case for create_entity

        """
        pass

    def test_list_entities(self):
        """Test case for list_entities

        """
        pass

    def test_remove_entity(self):
        """Test case for remove_entity

        """
        pass

    def test_replace_all_entity_attributes(self):
        """Test case for replace_all_entity_attributes

        """
        pass

    def test_retrieve_entity(self):
        """Test case for retrieve_entity

        """
        pass

    def test_retrieve_entity_attributes(self):
        """Test case for retrieve_entity_attributes

        """
        pass

    def test_update_existing_entity_attributes(self):
        """Test case for update_existing_entity_attributes

        """
        pass

    def test_update_or_append_entity_attributes(self):
        """Test case for update_or_append_entity_attributes

        """
        pass


if __name__ == '__main__':
    unittest.main()
