# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_v2
from ngsi_v2.models.api_entry_point import APIEntryPoint  # noqa: E501
from ngsi_v2.rest import ApiException


class TestAPIEntryPoint(unittest.TestCase):
    """APIEntryPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIEntryPoint(self):
        """Test APIEntryPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ngsi_v2.models.api_entry_point.APIEntryPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
