# coding: utf-8

"""
    ngsi_timeseries_v2

    QuantumLeap API  # noqa: E501

    The version of the OpenAPI document: 0.1.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class IndexedEntityTypeAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entities': 'list[EntityIndexedValues]',
        'entity_type': 'str',
        'attr_name': 'str'
    }

    attribute_map = {
        'entities': 'entities',
        'entity_type': 'entityType',
        'attr_name': 'attrName'
    }

    def __init__(self, entities=None, entity_type=None, attr_name=None):  # noqa: E501
        """IndexedEntityTypeAttribute - a model defined in OpenAPI"""  # noqa: E501

        self._entities = None
        self._entity_type = None
        self._attr_name = None
        self.discriminator = None

        if entities is not None:
            self.entities = entities
        if entity_type is not None:
            self.entity_type = entity_type
        if attr_name is not None:
            self.attr_name = attr_name

    @property
    def entities(self):
        """Gets the entities of this IndexedEntityTypeAttribute.  # noqa: E501


        :return: The entities of this IndexedEntityTypeAttribute.  # noqa: E501
        :rtype: list[EntityIndexedValues]
        """
        return self._entities

    @entities.setter
    def entities(self, entities):
        """Sets the entities of this IndexedEntityTypeAttribute.


        :param entities: The entities of this IndexedEntityTypeAttribute.  # noqa: E501
        :type: list[EntityIndexedValues]
        """

        self._entities = entities

    @property
    def entity_type(self):
        """Gets the entity_type of this IndexedEntityTypeAttribute.  # noqa: E501


        :return: The entity_type of this IndexedEntityTypeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this IndexedEntityTypeAttribute.


        :param entity_type: The entity_type of this IndexedEntityTypeAttribute.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def attr_name(self):
        """Gets the attr_name of this IndexedEntityTypeAttribute.  # noqa: E501


        :return: The attr_name of this IndexedEntityTypeAttribute.  # noqa: E501
        :rtype: str
        """
        return self._attr_name

    @attr_name.setter
    def attr_name(self, attr_name):
        """Sets the attr_name of this IndexedEntityTypeAttribute.


        :param attr_name: The attr_name of this IndexedEntityTypeAttribute.  # noqa: E501
        :type: str
        """

        self._attr_name = attr_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndexedEntityTypeAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
