# coding: utf-8

"""
    ngsi_timeseries_v2

    QuantumLeap API  # noqa: E501

    The version of the OpenAPI document: 0.1.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_timeseries_v2
from ngsi_timeseries_v2.models.attribute_values import AttributeValues  # noqa: E501
from ngsi_timeseries_v2.rest import ApiException


class TestAttributeValues(unittest.TestCase):
    """AttributeValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeValues(self):
        """Test AttributeValues"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ngsi_timeseries_v2.models.attribute_values.AttributeValues()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
