# coding: utf-8

"""
    ngsi_timeseries_v2

    QuantumLeap API  # noqa: E501

    The version of the OpenAPI document: 0.1.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_timeseries_v2
from ngsi_timeseries_v2.models.indexed_entity_attribute import IndexedEntityAttribute  # noqa: E501
from ngsi_timeseries_v2.rest import ApiException


class TestIndexedEntityAttribute(unittest.TestCase):
    """IndexedEntityAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexedEntityAttribute(self):
        """Test IndexedEntityAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ngsi_timeseries_v2.models.indexed_entity_attribute.IndexedEntityAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
