# coding: utf-8

"""
    ngsi_timeseries_v2

    QuantumLeap API  # noqa: E501

    The version of the OpenAPI document: 0.1.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ngsi_timeseries_v2
from ngsi_timeseries_v2.api.input_api import InputApi  # noqa: E501
from ngsi_timeseries_v2.rest import ApiException


class TestInputApi(unittest.TestCase):
    """InputApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_timeseries_v2.api.input_api.InputApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reporter_delete_delete_entities(self):
        """Test case for reporter_delete_delete_entities

        Delete historical data of all entities of a certain type.  # noqa: E501
        """
        pass

    def test_reporter_delete_delete_entity(self):
        """Test case for reporter_delete_delete_entity

        Delete historical data of a certain entity.  # noqa: E501
        """
        pass

    def test_reporter_reporter_notify(self):
        """Test case for reporter_reporter_notify

        Notify QuantumLeap the arrival of a new NGSI notification.  # noqa: E501
        """
        pass

    def test_reporter_reporter_subscribe(self):
        """Test case for reporter_reporter_subscribe

        Subscribe QL to process Orion notifications of certain type.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
