/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValuesArray from './ValuesArray';

/**
 * The AttributeValues model module.
 * @module model/AttributeValues
 * @version 0.1.2
 */
class AttributeValues {
  /**
   * Constructs a new <code>AttributeValues</code>.
   * @alias module:model/AttributeValues
   */
  constructor() {
    AttributeValues.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>AttributeValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttributeValues} obj Optional instance to populate.
   * @return {module:model/AttributeValues} The populated <code>AttributeValues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AttributeValues();

      if (data.hasOwnProperty('attrName')) {
        obj['attrName'] = ApiClient.convertToType(data['attrName'], 'String');
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ValuesArray.constructFromObject(data['values']);
      }
    }
    return obj;
  }
}

/**
 * @member {String} attrName
 */
AttributeValues.prototype['attrName'] = undefined;

/**
 * @member {module:model/ValuesArray} values
 */
AttributeValues.prototype['values'] = undefined;

export default AttributeValues;
