/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IndexedAllAttribute model module.
 * @module model/IndexedAllAttribute
 * @version 0.1.2
 */
class IndexedAllAttribute extends Array {
  /**
   * Constructs a new <code>IndexedAllAttribute</code>.
   * @alias module:model/IndexedAllAttribute
   * @extends Array
   */
  constructor() {
    super();

    IndexedAllAttribute.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>IndexedAllAttribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndexedAllAttribute} obj Optional instance to populate.
   * @return {module:model/IndexedAllAttribute} The populated <code>IndexedAllAttribute</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IndexedAllAttribute();

      ApiClient.constructFromObject(data, obj, 'Object');
    }
    return obj;
  }
}

export default IndexedAllAttribute;
