/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IndexArray from './IndexArray';
import ValuesArray from './ValuesArray';

/**
 * The IndexedValues model module.
 * @module model/IndexedValues
 * @version 0.1.2
 */
class IndexedValues {
  /**
   * Constructs a new <code>IndexedValues</code>.
   * @alias module:model/IndexedValues
   */
  constructor() {
    IndexedValues.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>IndexedValues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndexedValues} obj Optional instance to populate.
   * @return {module:model/IndexedValues} The populated <code>IndexedValues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IndexedValues();

      if (data.hasOwnProperty('index')) {
        obj['index'] = IndexArray.constructFromObject(data['index']);
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ValuesArray.constructFromObject(data['values']);
      }
    }
    return obj;
  }
}

/**
 * @member {module:model/IndexArray} index
 */
IndexedValues.prototype['index'] = undefined;

/**
 * @member {module:model/ValuesArray} values
 */
IndexedValues.prototype['values'] = undefined;

export default IndexedValues;
