/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IndexedAttributeValue model module.
 * @module model/IndexedAttributeValue
 * @version 0.1.2
 */
class IndexedAttributeValue extends Array {
  /**
   * Constructs a new <code>IndexedAttributeValue</code>.
   * @alias module:model/IndexedAttributeValue
   * @extends Array
   */
  constructor() {
    super();

    IndexedAttributeValue.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>IndexedAttributeValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndexedAttributeValue} obj Optional instance to populate.
   * @return {module:model/IndexedAttributeValue} The populated <code>IndexedAttributeValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IndexedAttributeValue();

      ApiClient.constructFromObject(data, obj, 'Object');
    }
    return obj;
  }
}

export default IndexedAttributeValue;
