/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entity from './Entity';

/**
 * The Notification model module.
 * @module model/Notification
 * @version 0.1.2
 */
class Notification {
  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @param data {Array.<module:model/Entity>}
   */
  constructor(data) {
    Notification.initialize(this, data);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, data) {
    obj['data'] = data;
  }

  /**
   * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notification} obj Optional instance to populate.
   * @return {module:model/Notification} The populated <code>Notification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Notification();

      if (data.hasOwnProperty('subscriptionId')) {
        obj['subscriptionId'] = ApiClient.convertToType(
          data['subscriptionId'],
          'String'
        );
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Entity]);
      }
    }
    return obj;
  }
}

/**
 * @member {String} subscriptionId
 */
Notification.prototype['subscriptionId'] = undefined;

/**
 * @member {Array.<module:model/Entity>} data
 */
Notification.prototype['data'] = undefined;

export default Notification;
