# coding: utf-8

"""
    iot_data

    IoT Data  # noqa: E501

    The version of the OpenAPI document: 1.9.0
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_data
from iot_data.models.any_value import AnyValue  # noqa: E501
from iot_data.rest import ApiException


class TestAnyValue(unittest.TestCase):
    """AnyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyValue(self):
        """Test AnyValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iot_data.models.any_value.AnyValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
