# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class QueryPattern(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'id_pattern': 'str',
        'type': 'str',
        'type_pattern': 'str'
    }

    attribute_map = {
        'id': 'id',
        'id_pattern': 'idPattern',
        'type': 'type',
        'type_pattern': 'typePattern'
    }

    def __init__(self, id=None, id_pattern=None, type=None, type_pattern=None):  # noqa: E501
        """QueryPattern - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._id_pattern = None
        self._type = None
        self._type_pattern = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if id_pattern is not None:
            self.id_pattern = id_pattern
        if type is not None:
            self.type = type
        if type_pattern is not None:
            self.type_pattern = type_pattern

    @property
    def id(self):
        """Gets the id of this QueryPattern.  # noqa: E501


        :return: The id of this QueryPattern.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QueryPattern.


        :param id: The id of this QueryPattern.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def id_pattern(self):
        """Gets the id_pattern of this QueryPattern.  # noqa: E501


        :return: The id_pattern of this QueryPattern.  # noqa: E501
        :rtype: str
        """
        return self._id_pattern

    @id_pattern.setter
    def id_pattern(self, id_pattern):
        """Sets the id_pattern of this QueryPattern.


        :param id_pattern: The id_pattern of this QueryPattern.  # noqa: E501
        :type: str
        """

        self._id_pattern = id_pattern

    @property
    def type(self):
        """Gets the type of this QueryPattern.  # noqa: E501


        :return: The type of this QueryPattern.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this QueryPattern.


        :param type: The type of this QueryPattern.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def type_pattern(self):
        """Gets the type_pattern of this QueryPattern.  # noqa: E501


        :return: The type_pattern of this QueryPattern.  # noqa: E501
        :rtype: str
        """
        return self._type_pattern

    @type_pattern.setter
    def type_pattern(self, type_pattern):
        """Sets the type_pattern of this QueryPattern.


        :param type_pattern: The type_pattern of this QueryPattern.  # noqa: E501
        :type: str
        """

        self._type_pattern = type_pattern

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryPattern):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
