# coding: utf-8

"""
    ngsi_v2

    NGSI V2 API RC-2018.07  # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: info@orchestracities.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SubscriptionBodySubject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entities': 'list[QueryPattern]',
        'conditions': 'SubscriptionBodySubjectConditions'
    }

    attribute_map = {
        'entities': 'entities',
        'conditions': 'conditions'
    }

    def __init__(self, entities=None, conditions=None):  # noqa: E501
        """SubscriptionBodySubject - a model defined in OpenAPI"""  # noqa: E501

        self._entities = None
        self._conditions = None
        self.discriminator = None

        if entities is not None:
            self.entities = entities
        if conditions is not None:
            self.conditions = conditions

    @property
    def entities(self):
        """Gets the entities of this SubscriptionBodySubject.  # noqa: E501


        :return: The entities of this SubscriptionBodySubject.  # noqa: E501
        :rtype: list[QueryPattern]
        """
        return self._entities

    @entities.setter
    def entities(self, entities):
        """Sets the entities of this SubscriptionBodySubject.


        :param entities: The entities of this SubscriptionBodySubject.  # noqa: E501
        :type: list[QueryPattern]
        """

        self._entities = entities

    @property
    def conditions(self):
        """Gets the conditions of this SubscriptionBodySubject.  # noqa: E501


        :return: The conditions of this SubscriptionBodySubject.  # noqa: E501
        :rtype: SubscriptionBodySubjectConditions
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this SubscriptionBodySubject.


        :param conditions: The conditions of this SubscriptionBodySubject.  # noqa: E501
        :type: SubscriptionBodySubjectConditions
        """

        self._conditions = conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionBodySubject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
