/**
 * ngsi_v2
 * NGSI V2 API RC-2018.07
 *
 * The version of the OpenAPI document: 0.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIEntryPoint from '../model/APIEntryPoint';
import ErrorResponse from '../model/ErrorResponse';

/**
 * APIEntryPoint service.
 * @module api/APIEntryPointApi
 * @version 0.2.2
 */
export default class APIEntryPointApi {
  /**
   * Constructs a new APIEntryPointApi.
   * @alias module:api/APIEntryPointApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the retrieveAPIResources operation.
   * @callback module:api/APIEntryPointApi~retrieveAPIResourcesCallback
   * @param {String} error Error message, if any.
   * @param {module:model/APIEntryPoint} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body. It is recommended to follow the \"url\" link values, [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve resources. Instead of constructing your own URLs, to keep your client decoupled from implementation details.
   * @param {module:api/APIEntryPointApi~retrieveAPIResourcesCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/APIEntryPoint}
   */
  retrieveAPIResources(callback) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = ['ApiKeyAuth', 'BearerAuth'];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = APIEntryPoint;
    return this.apiClient.callApi(
      '/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }
}
