/**
 * ngsi_v2
 * NGSI V2 API RC-2018.07
 *
 * The version of the OpenAPI document: 0.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Attribute from '../model/Attribute';
import ErrorResponse from '../model/ErrorResponse';

/**
 * Attributes service.
 * @module api/AttributesApi
 * @version 0.2.2
 */
export default class AttributesApi {
  /**
   * Constructs a new AttributesApi.
   * @alias module:api/AttributesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the getAttributeData operation.
   * @callback module:api/AttributesApi~getAttributeDataCallback
   * @param {String} error Error message, if any.
   * @param {module:model/Attribute} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Returns a JSON object with the attribute data of the attribute. The object follows the JSON Representation for attributes  (described in [JSON Entity Representation](https://fiware.github.io/specifications/ngsiv2/stable)  section). Response: * Successful operation uses 200 OK. * Errors use a non-2xx and (optionally) an error payload. See subsection   on [Error Responses](https://fiware.github.io/specifications/ngsiv2/stable)   for more details.
   * @param {String} entityId Id of the entity
   * @param {String} attrName Name of the attribute to be retrieved.
   * @param {Object} opts Optional parameters
   * @param {String} opts.fiwareService
   * @param {String} opts.fiwareServicePath
   * @param {String} opts.type Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
   * @param {String} opts.metadata A list of metadata names to include in the response. See [Filtering out attributes and metadata](https://fiware.github.io/specifications/ngsiv2/stable) section for more detail.
   * @param {module:api/AttributesApi~getAttributeDataCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/Attribute}
   */
  getAttributeData(entityId, attrName, opts, callback) {
    opts = opts || {};
    const postBody = null;
    // verify the required parameter 'entityId' is set
    if (entityId === undefined || entityId === null) {
      throw new Error(
        "Missing the required parameter 'entityId' when calling getAttributeData"
      );
    }
    // verify the required parameter 'attrName' is set
    if (attrName === undefined || attrName === null) {
      throw new Error(
        "Missing the required parameter 'attrName' when calling getAttributeData"
      );
    }

    const pathParams = {
      entityId,
      attrName,
    };
    const queryParams = {
      type: opts.type,
      metadata: opts.metadata,
    };
    const headerParams = {
      'Fiware-Service': opts.fiwareService,
      'Fiware-ServicePath': opts.fiwareServicePath,
    };
    const formParams = {};

    const authNames = ['ApiKeyAuth', 'BearerAuth'];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = Attribute;
    return this.apiClient.callApi(
      '/entities/{entityId}/attrs/{attrName}',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the removeASingleAttribute operation.
   * @callback module:api/AttributesApi~removeASingleAttributeCallback
   * @param {String} error Error message, if any.
   * @param data This operation does not return a value.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Removes an entity attribute. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection   on [Error Responses](https://fiware.github.io/specifications/ngsiv2/stable)   for more details.
   * @param {String} entityId Id of the entity.
   * @param {String} attrName Attribute name.
   * @param {Object} opts Optional parameters
   * @param {String} opts.fiwareService
   * @param {String} opts.fiwareServicePath
   * @param {String} opts.type Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
   * @param {module:api/AttributesApi~removeASingleAttributeCallback} callback The callback function, accepting three arguments: error, data, response
   */
  removeASingleAttribute(entityId, attrName, opts, callback) {
    opts = opts || {};
    const postBody = null;
    // verify the required parameter 'entityId' is set
    if (entityId === undefined || entityId === null) {
      throw new Error(
        "Missing the required parameter 'entityId' when calling removeASingleAttribute"
      );
    }
    // verify the required parameter 'attrName' is set
    if (attrName === undefined || attrName === null) {
      throw new Error(
        "Missing the required parameter 'attrName' when calling removeASingleAttribute"
      );
    }

    const pathParams = {
      entityId,
      attrName,
    };
    const queryParams = {
      type: opts.type,
    };
    const headerParams = {
      'Fiware-Service': opts.fiwareService,
      'Fiware-ServicePath': opts.fiwareServicePath,
    };
    const formParams = {};

    const authNames = ['ApiKeyAuth', 'BearerAuth'];
    const contentTypes = [];
    const accepts = ['application/json'];
    const returnType = null;
    return this.apiClient.callApi(
      '/entities/{entityId}/attrs/{attrName}',
      'DELETE',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the updateAttributeData operation.
   * @callback module:api/AttributesApi~updateAttributeDataCallback
   * @param {String} error Error message, if any.
   * @param data This operation does not return a value.
   * @param {String} response The complete HTTP response.
   */

  /**
   * The request payload is an object representing the new attribute data. Previous attribute data is replaced by the one in the request. The object follows the JSON Representation for attributes (described in [JSON Attribute Representation](https://fiware.github.io/specifications/ngsiv2/stable) section). Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection   on [Error Responses](https://fiware.github.io/specifications/ngsiv2/stable)   for more details.
   * @param {String} entityId Id of the entity to update
   * @param {String} attrName Attribute name
   * @param {module:model/Attribute} attribute
   * @param {Object} opts Optional parameters
   * @param {String} opts.fiwareService
   * @param {String} opts.fiwareServicePath
   * @param {String} opts.type Entity type, to avoid ambiguity in case there are several entities with the same entity id.
   * @param {module:api/AttributesApi~updateAttributeDataCallback} callback The callback function, accepting three arguments: error, data, response
   */
  updateAttributeData(entityId, attrName, attribute, opts, callback) {
    opts = opts || {};
    const postBody = attribute;
    // verify the required parameter 'entityId' is set
    if (entityId === undefined || entityId === null) {
      throw new Error(
        "Missing the required parameter 'entityId' when calling updateAttributeData"
      );
    }
    // verify the required parameter 'attrName' is set
    if (attrName === undefined || attrName === null) {
      throw new Error(
        "Missing the required parameter 'attrName' when calling updateAttributeData"
      );
    }
    // verify the required parameter 'attribute' is set
    if (attribute === undefined || attribute === null) {
      throw new Error(
        "Missing the required parameter 'attribute' when calling updateAttributeData"
      );
    }

    const pathParams = {
      entityId,
      attrName,
    };
    const queryParams = {
      type: opts.type,
    };
    const headerParams = {
      'Fiware-Service': opts.fiwareService,
      'Fiware-ServicePath': opts.fiwareServicePath,
    };
    const formParams = {};

    const authNames = ['ApiKeyAuth', 'BearerAuth'];
    const contentTypes = ['application/json'];
    const accepts = ['application/json'];
    const returnType = null;
    return this.apiClient.callApi(
      '/entities/{entityId}/attrs/{attrName}',
      'PUT',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }
}
