/**
 * iot-data
 * IoT Data
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnyValue model module.
 * @module model/AnyValue
 * @version 1.9.0
 */
class AnyValue {
  /**
   * Constructs a new <code>AnyValue</code>.
   * @alias module:model/AnyValue
   */
  constructor() {
    AnyValue.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>AnyValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnyValue} obj Optional instance to populate.
   * @return {module:model/AnyValue} The populated <code>AnyValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnyValue();
    }
    return obj;
  }
}

export default AnyValue;
