/**
 * ngsi_timeseries_v2
 * QuantumLeap API
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgsiTimeseriesV2);
  }
})(this, function(expect, NgsiTimeseriesV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgsiTimeseriesV2.MetaApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('MetaApi', function() {
    describe('reporterHealthGetHealth', function() {
      it('should call reporterHealthGetHealth successfully', function(done) {
        //uncomment below and update the code to test reporterHealthGetHealth
        //instance.reporterHealthGetHealth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reporterReporterConfig', function() {
      it('should call reporterReporterConfig successfully', function(done) {
        //uncomment below and update the code to test reporterReporterConfig
        //instance.reporterReporterConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reporterVersionVersion', function() {
      it('should call reporterVersionVersion successfully', function(done) {
        //uncomment below and update the code to test reporterVersionVersion
        //instance.reporterVersionVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });
});
