/**
 * ngsi_v2
 * NGSI V2 API RC-2018.07
 *
 * The version of the OpenAPI document: 0.2.2
 * Contact: info@orchestracities.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIEntryPoint model module.
 * @module model/APIEntryPoint
 * @version 0.2.2
 */
class APIEntryPoint {
  /**
   * Constructs a new <code>APIEntryPoint</code>.
   * @alias module:model/APIEntryPoint
   * @param entitiesUrl {String} URL which points to the entities resource
   * @param typesUrl {String} URL which points to the types resource
   * @param subscriptionsUrl {String} URL which points to the subscriptions resource
   * @param registrationsUrl {String} URL which points to the registrations resource
   */
  constructor(entitiesUrl, typesUrl, subscriptionsUrl, registrationsUrl) {
    APIEntryPoint.initialize(
      this,
      entitiesUrl,
      typesUrl,
      subscriptionsUrl,
      registrationsUrl
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    entitiesUrl,
    typesUrl,
    subscriptionsUrl,
    registrationsUrl
  ) {
    obj['entities_url'] = entitiesUrl;
    obj['types_url'] = typesUrl;
    obj['subscriptions_url'] = subscriptionsUrl;
    obj['registrations_url'] = registrationsUrl;
  }

  /**
   * Constructs a <code>APIEntryPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIEntryPoint} obj Optional instance to populate.
   * @return {module:model/APIEntryPoint} The populated <code>APIEntryPoint</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new APIEntryPoint();

      if (data.hasOwnProperty('entities_url')) {
        obj['entities_url'] = ApiClient.convertToType(
          data['entities_url'],
          'String'
        );
      }
      if (data.hasOwnProperty('types_url')) {
        obj['types_url'] = ApiClient.convertToType(data['types_url'], 'String');
      }
      if (data.hasOwnProperty('subscriptions_url')) {
        obj['subscriptions_url'] = ApiClient.convertToType(
          data['subscriptions_url'],
          'String'
        );
      }
      if (data.hasOwnProperty('registrations_url')) {
        obj['registrations_url'] = ApiClient.convertToType(
          data['registrations_url'],
          'String'
        );
      }
    }
    return obj;
  }
}

/**
 * URL which points to the entities resource
 * @member {String} entities_url
 */
APIEntryPoint.prototype['entities_url'] = undefined;

/**
 * URL which points to the types resource
 * @member {String} types_url
 */
APIEntryPoint.prototype['types_url'] = undefined;

/**
 * URL which points to the subscriptions resource
 * @member {String} subscriptions_url
 */
APIEntryPoint.prototype['subscriptions_url'] = undefined;

/**
 * URL which points to the registrations resource
 * @member {String} registrations_url
 */
APIEntryPoint.prototype['registrations_url'] = undefined;

export default APIEntryPoint;
