/**
 * ngsi_v2
 * NGSI V2 API RC-2018.07
 *
 * The version of the OpenAPI document: 0.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryPattern model module.
 * @module model/QueryPattern
 * @version 0.2.2
 */
class QueryPattern {
  /**
   * Constructs a new <code>QueryPattern</code>.
   * @alias module:model/QueryPattern
   */
  constructor() {
    QueryPattern.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>QueryPattern</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueryPattern} obj Optional instance to populate.
   * @return {module:model/QueryPattern} The populated <code>QueryPattern</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QueryPattern();

      if (data.hasOwnProperty('id')) {
        obj.id = ApiClient.convertToType(data.id, 'String');
      }
      if (data.hasOwnProperty('idPattern')) {
        obj.idPattern = ApiClient.convertToType(data.idPattern, 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj.type = ApiClient.convertToType(data.type, 'String');
      }
      if (data.hasOwnProperty('typePattern')) {
        obj.typePattern = ApiClient.convertToType(data.typePattern, 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
QueryPattern.prototype.id = undefined;

/**
 * @member {String} idPattern
 */
QueryPattern.prototype.idPattern = undefined;

/**
 * @member {String} type
 */
QueryPattern.prototype.type = undefined;

/**
 * @member {String} typePattern
 */
QueryPattern.prototype.typePattern = undefined;

export default QueryPattern;
