/**
 * ngsi_v2
 * NGSI V2 API RC-2018.07
 *
 * The version of the OpenAPI document: 0.2.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionBodyNotificationHttp model module.
 * @module model/SubscriptionBodyNotificationHttp
 * @version 0.2.2
 */
class SubscriptionBodyNotificationHttp {
  /**
   * Constructs a new <code>SubscriptionBodyNotificationHttp</code>.
   * @alias module:model/SubscriptionBodyNotificationHttp
   */
  constructor() {
    SubscriptionBodyNotificationHttp.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>SubscriptionBodyNotificationHttp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionBodyNotificationHttp} obj Optional instance to populate.
   * @return {module:model/SubscriptionBodyNotificationHttp} The populated <code>SubscriptionBodyNotificationHttp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionBodyNotificationHttp();

      if (data.hasOwnProperty('url')) {
        obj.url = ApiClient.convertToType(data.url, 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
SubscriptionBodyNotificationHttp.prototype.url = undefined;

export default SubscriptionBodyNotificationHttp;
